import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typewriter from 'typewriter-effect';

<Typewriter
  options={{
    strings: ['Hello', 'World'],
    autoStart: true,
    loop: true,
  }}
/>



export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          I am <a href="https://github.com/nabeeltahirdeveloper"><Typewriter
            options={
              {
                strings: ['Nabeel Tahir', 'Developer', 'Software Engineer'],
                autoStart: true,
                loop: true,
                speed: 80,
                delay: 40,
              }
            }
            styles={{
              display: 'inline-block',
            }}
          />
          </a>
        </h1>

      


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Nabeel
        </a>
      </footer>
    </div>
  )
}
